language: android
sudo: true
jdk: oraclejdk7

android:
  components:
  #- platform-tools
  #- tools
  - build-tools-21.1.1
  - android-21

  # Additional components
  #- extra-google-m2repository
  #- extra-android-m2repository
  #- extra-android-support

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/caches/jars-1
    - $HOME/.gradle/daemon
    - $HOME/.gradle/wrapper

script:
  - gradle build
  - ./gradlew assemble